unstable_features = true
wrap_comments = true
edition = "2021"
imports_granularity = "Crate"
newline_style = "Unix"
reorder_imports = true
group_imports = "StdExternalCrate"
max_width = 88
format_code_in_doc_comments = true
doc_comment_code_block_width=30
format_strings=true
comment_width=88
